apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo
  template:
    metadata:
      labels:
        app: abstergo
    spec:
      containers:
      - name: abstergo-container
        image: shadowdoc07/abstergo-demo:latest
        ports:
        - containerPort: 80
